// export const SET_ADMIN_SOURCE_INFO = 'SET_ADMIN_SOURCE_INFO';
export const SET_ADMIN_PRODUCTS = 'SET_ADMIN_PRODUCTS';
export const SET_ADMIN_PRODUCTS_MENU = 'SET_ADMIN_PRODUCTS_MENU';
export const SET_ADMIN_INFO = 'SET_ADMIN_INFO';
export const SET_ADMIN_PRODUCT_SELECTED = 'SET_ADMIN_PRODUCT_SELECTED';
export const SET_ADMIN_APP_SELECTED = 'SET_ADMIN_APP_SELECTED';
export const SET_ADMIN_APPS = 'SET_ADMIN_APPS';
export const SET_ADMIN_PERMISSIONS = 'SET_ADMIN_PERMISSIONS';
