export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const SET_SIDEBAR_MENUS = 'SET_SIDEBAR_MENUS';
export const SET_SIDEBAR_PRODUCT = 'SET_SIDEBAR_PRODUCT';

export const OPEN_FULLVIEW = 'OPEN_FULLVIEW';
export const CLOSE_FULLVIEW = 'CLOSE_FULLVIEW';
export const TOGGLE_FULLVIEW = 'TOGGLE_FULLVIEW';

export const OPEN_FEEDBACK = 'OPEN_FEEDBACK';
export const CLOSE_FEEDBACK = 'CLOSE_FEEDBACK';
export const FEEDBACK_LOADING = 'FEEDBACK_LOADING';
export const FEEDBACK_LOADED = 'FEEDBACK_LOADED';

export const OPEN_PRODUCTS = 'OPEN_PRODUCTS';
export const CLOSE_PRODUCTS = 'CLOSE_PRODUCTS';
export const TOGGLE_PRODUCTS = 'TOGGLE_PRODUCTS';

// export const SET_VIEWPORT_SIZE = 'SET_VIEWPORT_SIZE';
export const SET_VIEWPORT = 'SET_VIEWPORT';
export const VIEWPORT_SCROLL_TO_TOP = 'VIEWPORT_SCROLL_TO_TOP';
export const VIEWPORT_SCROLL_TO_BOTTOM = 'VIEWPORT_SCROLL_TO_BOTTOM';

