export const UPDATE_READED_LIST = 'UPDATE_ADMIN_MSG_READED_LIST';
export const UPDATE_UNREAD_LIST = 'UPDATE_ADMIN_MSG_UNREAD_LIST';
export const UPDATE_UNREADS_TO_READEDS = 'UPDATE_UNREADS_TO_READEDS';
export const DROP_UNREADS_AND_READEDS = 'DROP_UNREADS_AND_READEDS';
